# Generated by Django 2.2.5 on 2019-09-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('max_participant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('max_participant', models.IntegerField()),
            ],
        ),
    ]
